In [1]:
import pandas as pd

In [6]:
salaries = pd.read_csv("C:\\commonfiles\\PSalaryData.csv")

In [7]:
salaries

Experience Years  Salary
0                1.1   39343
1                1.2   42774
2                1.3   46205
3                1.5   37731
4                2.0   43525
5                2.2   39891
6                2.5   48266
7                2.9   56642
8                3.0   60150
9                3.2   54445
10               3.2   64445
11               3.5   60000
12               3.7   57189
13               3.8   60200
14               3.9   63218
15               4.0   55794
16               4.0   56957
17               4.1   57081
18               4.3   59095
19               4.5   61111
20               4.7   64500
21               4.9   67938
22               5.1   66029
23               5.3   83088
24               5.5   82200
25               5.9   81363
26               6.0   93940
27               6.2   91000
28               6.5   90000
29               6.8   91738
30               7.1   98273
31               7.9  101302
32               8.2  113812
33               8.5  111620
34               8.7  109431
35               9.0  105582
36               9.5  116969
37               9.6  112635
38              10.3  122391
39              10.5  121872

In [8]:
y=salaries['Salary']

In [10]:
x=salaries[['Experience Years']]

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.7,random_state=2529)

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
model = LinearRegression()

In [16]:
model.fit(X_train,Y_train)

LinearRegression()

In [17]:
model.intercept_

26596.961311068262

In [18]:
model.coef_


array([9405.61663234])

In [19]:
y_pred = model.predict(X_test)

In [20]:
y_pred

array([ 90555.15441095,  59516.61952424, 106544.70268592,  64219.42784041,
        68922.23615658, 123474.81262412,  84911.78443155,  63278.86617718,
        65159.98950364,  61397.74285071,  37883.70126987,  50111.00289191])

In [21]:
X_test

Experience Years
29               6.8
11               3.5
33               8.5
16               4.0
19               4.5
38              10.3
27               6.2
14               3.9
17               4.1
12               3.7
1                1.2
6                2.5

In [24]:
expected =model.predict(8 4.9)


SyntaxError: invalid syntax. Perhaps you forgot a comma? (789122879.py, line 1)

In [25]:
import numpy as np

In [26]:
expected =np.array([3])
expected= expected.reshape(1,1)

In [33]:
expected

array([[3]])

In [27]:
required = model.predict(expected)

C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [28]:
required

array([54813.81120807])

In [34]:
sudha=model.predict([[4.9]])

C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [35]:
sudha

array([72684.48280951])